### PR TITLE
Add additional hooks and public settings API

### PR DESCRIPTION
**Pull request by hailwood**
To allow this module to be easily extended we need a few hooks and access to the settings.

This pull request has the following changes:
- Change `getSetting()` access level to `public`
- Add `public` method `setSetting($setting, $value)`
- Add `onBeforeRender` hook to `FieldHolder()` method
- Add `updateAttachedFiles` hook to `AttachedFiles()` method
- Fix inconsistent tab vs space formatting

### CODE REVIEW

**Comment by hailwood** [comment]
https://packagist.org/packages/webfox/silverstripe-dropzone-sortable is ready to go pending this pull request :)

**Comment by hailwood** [comment]
@unclecheese Any chance of this getting merged in soon?

**Comment by unclecheese** [comment]
Yeah, looks good. I just have an issue with the exposure of `$settings`. The getter is fine, but the `setSetting()` method adds complexity and redundancy to the API. For example, `setUploadMultiple(true)` and `setSetting('uploadMultiple', true)` are now functionally equivalent. The reason I have explicit methods for all the settings is because often times they do sanitisation or formatting that should be transparent to the user. I would really prefer that those methods are the only way into the `$settings` array.

That said, an alternate way to solve your problem would be to provide an `updateSettings(&$settings)` hook to the extension. What do you think? It could go in `FieldHolder() ` to ensure that setttings will not be mutated after that.

**Comment by SilbinaryWolf** [comment]
@hailwood Are you going to fix this?

**Pull request closed without merging**
